import{buildPlanContext,createCheckin,recordFromCheckin,saveRecord,basketballRecord,parseRawRecords,normalizeRecords,nextUnchecked,mergeRecords}from'./training.js?v=16';
import{buildAnalysis,fmtPct}from'./analysis.js?v=16';
import{PLAN_LIBRARY,RAW_RECORDS,APP_VERSION}from'./data.js?v=16';
const $=(s,r=document)=>r.querySelector(s),el=(t,c)=>{const n=document.createElement(t);if(c)n.className=c;return n};
function fmtTime(s){s=Math.max(0,Math.floor(s));const h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor(s%3600/60)).padStart(2,'0'),x=String(s%60).padStart(2,'0');return`${h}:${m}:${x}`}
function fmtRest(s){s=Math.max(0,Math.ceil(s));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function svgLine(points){if(!points.length)return'<div class="chart-note">暂无数据</div>';const w=320,h=150,p=24,max=Math.max(...points.map(x=>x.value),1),step=(w-p*2)/(Math.max(1,points.length-1));const xy=points.map((d,i)=>[p+i*step,p+(h-p*2)*(1-d.value/max),d]);const path=xy.map((p,i)=>`${i?'L':'M'}${p[0]},${p[1]}`).join(' ');return`<svg class="svg-chart" viewBox="0 0 ${w} ${h}"><path d="M${p},${h-p} ${xy.map(q=>`L${q[0]},${q[1]}`).join(' ')} L${xy.at(-1)[0]},${h-p}Z" fill="rgba(88,208,255,.18)"/><path d="${path}" fill="none" stroke="url(#g)" stroke-width="4" stroke-linecap="round"/><defs><linearGradient id="g"><stop stop-color="#58d0ff"/><stop offset="1" stop-color="#8af4cf"/></linearGradient></defs>${xy.map(q=>`<circle cx="${q[0]}" cy="${q[1]}" r="4" fill="#15324a" stroke="#fff" stroke-width="2"/>`).join('')}${xy.map((q,i)=>i%2||i===0||i===xy.length-1?`<text x="${q[0]}" y="${h-6}" font-size="10" text-anchor="middle" fill="#718096">${q[2].label}</text>`:'').join('')}</svg>`}
function svgBars(labels,values){const w=320,h=150,p=24,max=Math.max(...values,1),gap=(w-p*2)/labels.length;return`<svg class="svg-chart" viewBox="0 0 ${w} ${h}">${labels.map((l,i)=>{const bw=Math.min(40,gap*.55),x=p+i*gap+(gap-bw)/2,bh=(h-p*2)*(values[i]/max),y=h-p-bh;return`<rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="14" fill="${['#58d0ff','#78efd0','#b8b1ff','#91b6ff'][i%4]}"/><text x="${x+bw/2}" y="${y-6}" font-size="10" text-anchor="middle" fill="#18324a">${Math.round(values[i])}</text><text x="${x+bw/2}" y="${h-6}" font-size="10" text-anchor="middle" fill="#718096">${l}</text>`}).join('')}</svg>`}
class RippleRenderer{constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.running=false;this.raf=0;this.t=0}resize(){const dpr=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect();this.canvas.width=r.width*dpr;this.canvas.height=r.height*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=r.width;this.h=r.height}start(){if(this.running)return;this.running=true;this.resize();this.loop()}stop(){this.running=false;cancelAnimationFrame(this.raf)}loop=()=>{if(!this.running)return;this.t+=.012;this.draw();this.raf=requestAnimationFrame(this.loop)};draw(){const c=this.ctx,w=this.w,h=this.h;c.clearRect(0,0,w,h);c.lineWidth=1;for(let i=0;i<8;i++){c.beginPath();c.strokeStyle=`rgba(76,176,224,${.055+i*.007})`;for(let x=-20;x<w+20;x+=8){const y=80+i*74+Math.sin(x*.018+this.t+i)*12+Math.sin(x*.041-this.t*1.6)*4;x===-20?c.moveTo(x,y):c.lineTo(x,y)}c.stroke()}}}
export class UIManager{
  constructor({state,storage,timer}){this.store=state;this.state=state.state;this.storage=storage;this.timer=timer;this.nodes={};this.modalResolve=null;this.ripple=null;this.saveQueued=false}
  mount(){this.cache();this.mergeDefaults(false);this.ensurePlan();this.bind();this.renderAll();this.ripple=new RippleRenderer(this.nodes.canvas);this.ripple.start();this.bindMotion();this.timer.on('tick',s=>this.renderTimers(s));this.timer.on('rest-done',()=>this.alarm());this.timer.startLoop();this.store.subscribe('*',()=>this.queueSave())}
  cache(){['planTitle','planDesc','todayLine','datePill','heroTags','progressRing','progressText','setCounter','planList','workTime','restTime','restState','restMeter','timerState','laps','archiveList','newLog','toast','modalRoot','modalTitle','modalMessage','analysisScore','analysisSummary','analysisPills','analysisRange','statsGrid','volumeChart','volumeNote','freqChart','freqNote','loadChart','loadNote','prChart','prNote','insights'].forEach(id=>this.nodes[id]=$( '#'+id));this.nodes.canvas=$('#waveCanvas')}
  bind(){document.addEventListener('click',e=>this.routeClick(e));document.addEventListener('input',e=>this.routeInput(e));addEventListener('resize',()=>this.ripple?.resize())}
  bindMotion(){document.addEventListener('visibilitychange',()=>{document.documentElement.classList.toggle('motion-paused',document.hidden);document.hidden?this.ripple.stop():this.ripple.start()})}
  queueSave(){if(this.saveQueued)return;this.saveQueued=true;queueMicrotask(()=>{this.storage.save(this.state);this.saveQueued=false})}
  mergeDefaults(show=true){const defaults=parseRawRecords(RAW_RECORDS);this.state.records=mergeRecords(this.state.records||[],defaults);this.state.defaultMergedVersion=APP_VERSION;if(show)this.toast('完整历史档案已合并')}
  ensurePlan(){const ctx=buildPlanContext(this.state.records,PLAN_LIBRARY);const key=`${ctx.date}-${ctx.type}`;this.state.activePlanKey=key;if(!this.state.checkins[key])this.state.checkins[key]=createCheckin(ctx)}
  current(){this.ensurePlan();return{ctx:buildPlanContext(this.state.records,PLAN_LIBRARY),checkin:this.state.checkins[this.state.activePlanKey]}}
  renderAll(){this.renderPlan();this.renderAnalysis();this.renderArchive();this.renderTimers(this.timer.snapshot())}
  renderPlan(){const{ctx,checkin}=this.current();this.nodes.planTitle.textContent=ctx.label;this.nodes.todayLine.textContent=ctx.line;this.nodes.datePill.textContent=ctx.date;this.nodes.planDesc.textContent=ctx.last?`计划日期 ${ctx.date} · 上次力量 ${ctx.last.date}，按你最新三分化模板动态加重。`:`计划日期 ${ctx.date} · 从胸肩三头开始。`;this.nodes.heroTags.replaceChildren(...['5.16起完整分析','最新三分化模板','动态递进'].map(x=>{const s=el('span');s.textContent=x;return s}));this.nodes.planList.replaceChildren(...ctx.exercises.map((ex,i)=>this.exerciseCard(ex,checkin.sets[i],i)));this.updateProgress()}
  exerciseCard(ex,state,i){const card=el('article','glass card');const box=el('div','exercise');card.append(box);const top=el('div','ex-top');top.innerHTML=`<div><div class="ex-name"></div><div class="target"></div></div><div class="ex-kind"></div>`;$('.ex-name',top).textContent=ex.name;$('.target',top).textContent=ex.target;$('.ex-kind',top).textContent=ex.type;box.append(top);const mg=el('div','mini-grid');mg.innerHTML=`<div class="mini"><span>推荐安排</span><b></b></div><div class="mini"><span>推荐逻辑</span><b>完成度高则末组试重</b></div>`;$('b',mg).textContent=ex.rec;box.append(mg);const head=el('div','set-head');head.innerHTML='<span></span><span>组数</span><span>重量/负荷</span><span>次数/时间</span>';box.append(head);const list=el('div','set-list');state.sets.forEach((s,j)=>list.append(this.setRow(s,i,j)));box.append(list);const tip=el('div','tip');tip.textContent=ex.tips;box.append(tip);const bar=el('div','bar');bar.append(el('i'));box.append(bar);return card}
  setRow(s,i,j){const r=el('div','set-row');r.dataset.exercise=i;r.dataset.set=j;r.classList.toggle('done',s.done);const b=el('button','set-check');b.dataset.action='toggle-set';b.textContent=s.done?'✓':'';const no=el('div','set-no');no.textContent=`第${j+1}组`;const w=el('input');w.value=s.weight;w.placeholder='重量';w.dataset.setInput='1';w.dataset.field='weight';const reps=el('input');reps.value=s.reps;reps.placeholder='次数/时间';reps.dataset.setInput='1';reps.dataset.field='reps';r.append(b,no,w,reps);return r}
  updateProgress(){const{checkin}=this.current();let done=0,total=0;checkin.sets.forEach(ex=>ex.sets.forEach(s=>{total++;if(s.done)done++}));const p=total?Math.round(done/total*100):0;this.nodes.progressText.textContent=p+'%';this.nodes.progressRing.style.setProperty('--p',p);this.nodes.setCounter.textContent=`${done}/${total} 组`;this.nodes.planList.querySelectorAll('.exercise').forEach((ex,i)=>{const st=checkin.sets[i],d=st.sets.filter(x=>x.done).length,t=st.sets.length;$('.bar i',ex).style.width=(t?d/t*100:0)+'%'})}
  toggleSet(row){const i=+row.dataset.exercise,j=+row.dataset.set;const s=this.current().checkin.sets[i].sets[j];s.done=!s.done;row.classList.toggle('done',s.done);$('.set-check',row).textContent=s.done?'✓':'';this.updateProgress()}
  routeInput(e){const input=e.target.closest('[data-set-input]');if(!input)return;const row=input.closest('.set-row'),i=+row.dataset.exercise,j=+row.dataset.set,field=input.dataset.field;this.current().checkin.sets[i].sets[j][field]=input.value}
  async routeClick(e){const btn=e.target.closest('[data-action]');if(!btn)return;this.addTouchRipple(e);const a=btn.dataset.action;if(a==='toggle-set')return this.toggleSet(btn.closest('.set-row'));if(a==='nav')return this.showTab(btn.dataset.tab,btn);if(a==='save-today')return this.saveToday();if(a==='reset-today')return this.resetToday();if(a==='skip-basketball')return this.skipBasketball();if(a==='add-log')return this.addLog();if(a==='export-data')return this.exportData();if(a==='restore-data')return this.restoreData();if(a==='merge-default')return this.mergeDefaults(true),this.renderAll();if(a==='clear-cache')return this.clearCache();if(a==='work-toggle')return this.timer.toggleWork();if(a==='work-reset')return this.timer.resetWork();if(a==='work-lap')return this.timer.lap();if(a==='rest-set')return this.timer.setRest(+btn.dataset.sec);if(a==='rest-custom')return this.timer.setRest(+$('#customSec').value||90);if(a==='rest-toggle')return this.timer.toggleRest();if(a==='rest-add')return this.timer.addRest(+btn.dataset.sec);if(a==='rest-reset')return this.timer.resetRest();if(a==='set-done-rest')return this.markSetAndRest();if(a==='notify-request')return this.requestNotify();if(a==='modal-confirm')return this.resolveModal(true);if(a==='modal-cancel')return this.resolveModal(false)}
  showTab(tab,btn){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===tab));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b===btn));if(tab==='analysis')this.renderAnalysis();if(tab==='archive')this.renderArchive()}
  saveToday(){const rec=recordFromCheckin(this.current().checkin);if(!rec.items.length)return this.toast('还没有勾选完成组');this.state.records=saveRecord(this.state.records,rec);delete this.state.checkins[this.state.activePlanKey];this.ensurePlan();this.renderAll();this.toast(`${rec.date} 已保存，计划和分析已更新`)}
  async resetToday(){if(!await this.confirm('确定清空今日打卡？','清空确认'))return;delete this.state.checkins[this.state.activePlanKey];this.ensurePlan();this.renderPlan()}
  skipBasketball(){const{ctx}=this.current();this.state.records=saveRecord(this.state.records,basketballRecord(ctx.date));delete this.state.checkins[this.state.activePlanKey];this.ensurePlan();this.renderAll();this.toast('已记录篮球/有氧')}
  addLog(){const txt=this.nodes.newLog.value.trim();if(!txt)return;const recs=parseRawRecords(txt);this.state.records=mergeRecords(this.state.records,recs);this.nodes.newLog.value='';this.renderAll();this.toast('已添加记录并更新分析')}
  exportData(){const blob=new Blob([JSON.stringify(this.state.records,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gym-vault-records.json';a.click();URL.revokeObjectURL(a.href)}
  async restoreData(){if(!await this.confirm('恢复默认档案会覆盖当前历史记录。','恢复默认'))return;this.state.records=normalizeRecords(parseRawRecords(RAW_RECORDS));this.state.checkins={};this.ensurePlan();this.renderAll()}
  async clearCache(){if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.update()))}const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));this.toast('缓存已刷新，重新打开网页生效')}
  markSetAndRest(){const pos=nextUnchecked(this.current().checkin);if(pos){const row=this.nodes.planList.querySelector(`.set-row[data-exercise="${pos[0]}"][data-set="${pos[1]}"]`);this.toggleSet(row)}this.timer.startRest()}
  renderTimers(s){this.nodes.workTime.textContent=fmtTime(s.work);this.nodes.timerState.textContent=s.workRunning?'训练中':'未开始';this.nodes.restTime.textContent=fmtRest(s.rest);this.nodes.restState.textContent=s.restRunning?'休息中':`已设定 ${s.restDuration} 秒`;this.nodes.restMeter.style.width=(s.restDuration?Math.max(0,Math.min(100,(1-s.rest/s.restDuration)*100)):0)+'%';this.nodes.laps.replaceChildren(...s.laps.slice(-5).map(l=>{const n=el('div','lap');n.textContent=`${l.at} · ${fmtTime(l.time)}`;return n}))}
  renderArchive(){this.nodes.archiveList.replaceChildren(...this.state.records.slice().reverse().map(r=>{const d=el('div','archive-day');const h=el('h3');h.textContent=r.date;d.append(h);r.items.forEach(i=>{const it=el('div','archive-item');const b=el('b');b.textContent=i.name;const p=el('p');p.textContent=(i.sets||[]).join(' / ');it.append(b,p);d.append(it)});return d}))}
  renderAnalysis(){const m=buildAnalysis(this.state.records);this.nodes.analysisScore.textContent=`训练成熟度 ${m.score}`;this.nodes.analysisRange.textContent=m.range;this.nodes.analysisSummary.textContent=`总训练量约 ${Math.round(m.total).toLocaleString()} kg·次；近端容量变化 ${fmtPct(m.trend)}。`;this.nodes.analysisPills.replaceChildren(...[`均次 ${m.avg.toLocaleString()}`,`推拉腿差 ${m.balance}`,`PR ${m.prs.length} 项`].map(x=>{const s=el('span');s.textContent=x;return s}));this.nodes.statsGrid.replaceChildren(...[[m.total,'校正训练量','双哑铃动作已×2'],[m.counts.胸肩三头+m.counts.背二头+m.counts.臀腿,'力量训练日','篮球不推进顺序'],[m.counts.篮球,'篮球有氧日','不计入力量模块'],[fmtPct(m.trend),'近端变化','最近3次 vs 最早3次']].map(a=>{const c=el('div','metric-card glass');c.innerHTML='<b></b><span></span><em></em>';c.children[0].textContent=typeof a[0]==='number'?Math.round(a[0]).toLocaleString():a[0];c.children[1].textContent=a[1];c.children[2].textContent=a[2];return c}));this.nodes.volumeChart.innerHTML=svgLine(m.vols);this.nodes.volumeNote.textContent='训练量从第一天到最新记录动态更新，按单只哑铃记录习惯校正。';this.nodes.freqChart.innerHTML=svgBars(['推','拉','腿','篮'],[m.counts.胸肩三头,m.counts.背二头,m.counts.臀腿,m.counts.篮球]);this.nodes.freqNote.textContent=m.balance<=1?'推拉腿频率比较均衡。':'近期模块频率有偏差，计划会按顺序修正。';this.nodes.loadChart.innerHTML=svgBars(['推','拉','腿'],[m.loads.胸肩三头,m.loads.背二头,m.loads.臀腿]);this.nodes.loadNote.textContent='负荷分布用于观察训练压力是否长期偏科。';this.nodes.prChart.innerHTML=svgBars(m.prs.slice(0,4).map(x=>x.name.slice(0,4)),m.prs.slice(0,4).map(x=>x.e));this.nodes.prNote.textContent=m.prs[0]?`当前最高估算强度：${m.prs[0].name}。`:'暂无 PR。';this.nodes.insights.replaceChildren(...m.insights.map((x,i)=>{const c=el('div','smart-card');c.innerHTML=`<h3>${['进步类型','训练容量','结构平衡','动作信号'][i]||'判断'}</h3><p></p>`;c.querySelector('p').textContent=x;return c}))}
  confirm(message,title='确认操作'){return new Promise(res=>{this.modalResolve=res;this.nodes.modalTitle.textContent=title;this.nodes.modalMessage.textContent=message;this.nodes.modalRoot.hidden=false})}
  resolveModal(v){this.nodes.modalRoot.hidden=true;this.modalResolve?.(v);this.modalResolve=null}
  toast(msg){this.nodes.toast.textContent=msg;this.nodes.toast.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.nodes.toast.classList.remove('show'),1800)}
  async requestNotify(){if('Notification'in window){const p=await Notification.requestPermission();this.toast(p==='granted'?'提醒已开启':'未允许提醒')}}
  alarm(){this.toast('组间休息结束');navigator.vibrate?.([200,80,200]);if(Notification?.permission==='granted')navigator.serviceWorker?.ready.then(r=>r.showNotification('组间休息结束',{body:'该回去训练了。'})).catch(()=>new Notification('组间休息结束'))}
  addTouchRipple(e){const r=el('i','touch-ripple'),rect=this.nodes.canvas.parentElement.getBoundingClientRect();r.style.left=e.clientX-rect.left+'px';r.style.top=e.clientY-rect.top+'px';r.style.width=r.style.height='28px';this.nodes.canvas.parentElement.append(r);setTimeout(()=>r.remove(),650)}
}