(()=>{
'use strict';
if(window.__GYM_ANALYSIS_CLEAN__)return;window.__GYM_ANALYSIS_CLEAN__=true;
const KEY='gym-vault-v36-cloud',YEAR=2026,$=(s,r=document)=>r.querySelector(s);
const ALIAS={'俯身飞鸟':'坐姿俯身反向飞鸟','俯身反向飞鸟':'坐姿俯身反向飞鸟','俯身哑铃飞鸟':'坐姿俯身反向飞鸟','坐姿俯身飞鸟':'坐姿俯身反向飞鸟','二头弯举':'靠腿二头弯举','靠腿弯举':'靠腿二头弯举','哑铃二头弯举':'靠腿二头弯举','保加利亚蹲':'保加利亚分腿蹲','箭步蹲':'原地箭步蹲','哑铃箭步蹲':'原地箭步蹲','臂屈伸':'过顶臂屈伸','坐姿臂屈伸':'过顶臂屈伸','哑铃侧平举':'侧平举','哑铃坐姿推肩':'坐姿推肩','哑铃平板卧推':'平板卧推'};
const CAT={'平板卧推':['Push',['胸','前三角','三头'],2,1],'上斜卧推':['Push',['上胸','前三角','三头'],2,1],'坐姿推肩':['Push',['前三角','三头','核心'],2,1],'侧平举':['Push',['侧三角'],2,.45],'过顶臂屈伸':['Push',['三头'],2,.55],'俯卧撑':['Push',['胸','前三角','三头'],1,.35],'高位下拉':['Pull',['背阔肌','二头'],1,1],'上斜划船':['Pull',['中背','背阔肌','后束'],2,1],'单臂哑铃划船':['Pull',['背阔肌','中背','二头'],1,.9],'双臂哑铃俯身划船':['Pull',['中背','背阔肌','后束'],2,1],'坐姿俯身反向飞鸟':['Pull',['后束','上背'],2,.4],'靠腿二头弯举':['Pull',['二头'],2,.55],'壶铃摆动':['Legs',['臀','后链','核心'],1,.8],'保加利亚分腿蹲':['Legs',['股四头','臀','稳定'],2,1],'原地箭步蹲':['Legs',['股四头','臀','稳定'],2,.85],'罗马尼亚硬拉':['Legs',['后链','臀','腘绳肌'],2,1],'平板支撑':['Legs',['核心'],1,.2],'平板支撑肩触碰':['Legs',['核心','稳定'],1,.35],'地面哑铃臀桥':['Legs',['臀','后链'],1,.75]};
const MAIN=['平板卧推','坐姿推肩','上斜卧推','高位下拉','上斜划船','双臂哑铃俯身划船','保加利亚分腿蹲','罗马尼亚硬拉','靠腿二头弯举'];
const canon=n=>ALIAS[(n||'').trim()]||(n||'').trim(),fmt=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:0}),fmt1=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:1});
function md(x){const [m,d]=String(x).split('.').map(Number);return new Date(YEAR,m-1,d)}function setp(s){s=String(s||'').replace(/×/g,'*');const a=(s.match(/[\d.]+/g)||[]).map(Number);if(/kg/i.test(s))return[a[0]||0,a[1]||0,a[2]||1];return[0,a[0]||0,a[1]||1]}
function data(){try{return (JSON.parse(localStorage.getItem(KEY)||'{}').records||[]).sort((a,b)=>md(a.date)-md(b.date))}catch{return[]}}
function moduleOf(items){const txt=(items||[]).map(i=>canon(i.name)).join(' ');if(txt.includes('篮球'))return'Basketball';if(/休息|休整/.test(txt))return'Rest';const s={Push:0,Pull:0,Legs:0};(items||[]).forEach(i=>{const c=CAT[canon(i.name)];if(c)s[c[0]]++});return Object.entries(s).sort((a,b)=>b[1]-a[1])[0]?.[1]?Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0]:'Other'}
function rows(rs){const out=[];rs.forEach(r=>(r.items||[]).forEach(i=>{const name=canon(i.name),c=CAT[name];if(!c)return;(i.sets||[]).forEach(raw=>{const [kg,reps,cnt]=setp(raw);for(let k=0;k<Math.max(1,cnt);k++){const vol=kg*reps*c[2],stim=vol*c[3];out.push({date:r.date,name,m:c[0],vol,stim,e:kg&&reps?kg*(1+reps/30):0,mus:c[1]})}})}));return out}
function med(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function css(){if($('#analysisCleanCss'))return;const s=document.createElement('style');s.id='analysisCleanCss';s.textContent='.dash{display:grid;gap:12px}.kpis{display:grid;grid-template-columns:1fr 1fr;gap:10px}.kpi{min-height:92px}.kpi small{display:block;color:var(--muted);font-size:11px;font-weight:900}.kpi b{display:block;font-size:24px}.rowbar{display:grid;grid-template-columns:76px 1fr 62px;gap:9px;align-items:center;padding:10px;border-radius:18px;background:rgba(255,255,255,.58);border:1px solid rgba(255,255,255,.74);margin-bottom:9px}.rowbar b{font-size:14px}.track{height:13px;border-radius:999px;background:rgba(45,80,116,.10);overflow:hidden}.track i{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--a),var(--b))}.rowbar span{text-align:right;font-size:12px;color:#53677d;font-weight:900}.badge{display:inline-block;border-radius:999px;padding:6px 9px;background:rgba(255,255,255,.62);border:1px solid rgba(255,255,255,.76);font-size:11px;font-weight:950;color:#2e6988;margin:3px 5px 3px 0}.note2{font-size:12px;line-height:1.65;color:#53677d;font-weight:780}@media(max-width:370px){.kpis{grid-template-columns:1fr}.rowbar{grid-template-columns:66px 1fr 52px}}';document.head.appendChild(s)}
function bar(obj,limit=6){let e=Object.entries(obj).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);const other=e.slice(limit).reduce((s,x)=>s+x[1],0);e=e.slice(0,limit);if(other)e.push(['其他',other]);const max=Math.max(1,...e.map(x=>x[1]));return e.map(([k,v])=>`<div class="rowbar"><b>${k}</b><div class="track"><i style="width:${Math.round(v/max*100)}%"></i></div><span>${fmt(v)}</span></div>`).join('')}
function render(){const a=$('#analysis');if(!a||!a.classList.contains('active'))return;css();const rs=data(),rr=rows(rs);if(!rs.length)return;const cnt={Push:0,Pull:0,Legs:0,Basketball:0,Rest:0},load={Push:0,Pull:0,Legs:0},mus={};rs.forEach(r=>cnt[moduleOf(r.items)]++);rr.forEach(x=>{load[x.m]+=x.stim;x.mus.forEach(m=>mus[m]=(mus[m]||0)+x.stim)});const total=rr.reduce((s,x)=>s+x.vol,0),strength=rs.filter(r=>!['Basketball','Rest'].includes(moduleOf(r.items))).length,avg=strength?total/strength:0;const prs=MAIN.map(n=>{const by={};rr.filter(x=>x.name===n&&x.e).forEach(x=>by[x.date]=Math.max(by[x.date]||0,x.e));const xs=Object.values(by);if(xs.length<2)return null;const base=med(xs.slice(0,2)),now=med(xs.slice(-2));return[n,base?now/base-1:0,xs.length]}).filter(Boolean).sort((a,b)=>b[1]-a[1]).slice(0,5);const last=[...rs].reverse().find(r=>!['Basketball','Rest'].includes(moduleOf(r.items))),seq=['Push','Pull','Legs'],lm=last?moduleOf(last.items):'Push',next=seq[(seq.indexOf(lm)+1)%3]||'Push';a.innerHTML=`<header class="head"><div><h1>训练分析</h1><p class="sub">${rs[0].date}–${rs.at(-1).date} · Clean Dashboard</p></div><div class="chip">PRO</div></header><div class="dash"><article class="glass card"><div class="kicker">OVERVIEW</div><p class="note2">当前 ${rs.length} 天记录，力量训练 ${strength} 次，有效力量组 ${rr.length} 组。分析按双哑铃动作、动作重要性和肌群刺激做校正。</p><span class="badge">总量 ${fmt(total)}</span><span class="badge">均次 ${fmt(avg)}</span><span class="badge">推${cnt.Push}</span><span class="badge">拉${cnt.Pull}</span><span class="badge">腿${cnt.Legs}</span><span class="badge">篮球${cnt.Basketball}</span></article><div class="kpis"><div class="glass card kpi"><small>平均力量日负荷</small><b>${fmt(avg)}</b><small>kg·次</small></div><div class="glass card kpi"><small>下一次力量</small><b>${next}</b><small>篮球/休息不推进</small></div></div><article class="glass card"><div class="section-title"><h2>模块刺激量</h2><span>校正后</span></div>${bar({推:load.Push,拉:load.Pull,腿:load.Legs},3)}</article><article class="glass card"><div class="section-title"><h2>肌群热区</h2><span>Top 6 + 其他</span></div>${bar(mus,6)}<p class="note2">这里不再堆一整列文字，只保留主要肌群和比例条。</p></article><article class="glass card"><div class="section-title"><h2>主项进步</h2><span>e1RM中位数</span></div>${prs.map(x=>`<div class="rowbar"><b>${x[0]}</b><div class="track"><i style="width:${Math.max(6,Math.min(100,Math.round((x[1]+.2)*100)))}%"></i></div><span>${Math.round(x[1]*100)}%</span></div>`).join('')}</article><div class="smart"><b>训练建议</b><p>最后力量日是 ${last?.date||'—'} 的 ${lm}。下一次建议 ${next}。主项先稳定完成目标次数，只有最后一组速度和动作都稳，再小幅加重。</p></div></div>`}
document.addEventListener('click',e=>{if(e.target.closest('[data-tab="analysis"]'))setTimeout(render,80)});setInterval(render,1200);window.addEventListener('focus',()=>setTimeout(render,120));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,120));else setTimeout(render,120);
})();