(()=>{
'use strict';
if(window.__GYM_ANALYSIS__) return;
window.__GYM_ANALYSIS__=true;
const KEY='gym-vault-v36-cloud',YEAR=2026;
const ALIAS={'哑铃平板卧推':'平板卧推','标准俯卧撑':'俯卧撑','窄距俯卧撑':'俯卧撑','哑铃坐姿推肩':'坐姿推肩','哑铃推肩':'坐姿推肩','哑铃侧平举':'侧平举','坐姿臂屈伸':'过顶臂屈伸','臂屈伸':'过顶臂屈伸','哑铃过顶臂屈伸':'过顶臂屈伸','双哑铃上斜划船':'上斜划船','上斜哑铃划船':'上斜划船','单臂划船':'单臂哑铃划船','哑铃划船':'单臂哑铃划船','俯身飞鸟':'坐姿俯身飞鸟','俯身反向飞鸟':'坐姿俯身飞鸟','俯身哑铃飞鸟':'坐姿俯身飞鸟','二头弯举':'靠腿二头弯举','靠腿弯举':'靠腿二头弯举','坐姿靠腿二头弯举':'靠腿二头弯举','哑铃二头弯举':'靠腿二头弯举','保加利亚蹲':'保加利亚分腿蹲','哑铃箭步蹲':'原地箭步蹲','箭步蹲':'原地箭步蹲','哑铃罗马尼亚硬拉':'罗马尼亚硬拉'};
const CAT={
'平板卧推':{m:'Push',mus:['胸','前三角','三头'],pat:'水平推',mul:2,imp:1},'上斜卧推':{m:'Push',mus:['上胸','前三角','三头'],pat:'上斜推',mul:2,imp:1},'坐姿推肩':{m:'Push',mus:['前三角','三头','核心'],pat:'垂直推',mul:2,imp:1},'侧平举':{m:'Push',mus:['中束'],pat:'肩外展',mul:2,imp:.45},'过顶臂屈伸':{m:'Push',mus:['三头'],pat:'肘伸',mul:2,imp:.55},'俯卧撑':{m:'Push',mus:['胸','前三角','三头'],pat:'自重推',mul:1,imp:.35},
'高位下拉':{m:'Pull',mus:['背阔肌','二头'],pat:'垂直拉',mul:1,imp:1},'上斜划船':{m:'Pull',mus:['中背','背阔肌','后束'],pat:'水平拉',mul:2,imp:1},'单臂哑铃划船':{m:'Pull',mus:['背阔肌','中背','二头'],pat:'单侧拉',mul:1,imp:.9},'双臂哑铃俯身划船':{m:'Pull',mus:['中背','背阔肌','后束'],pat:'俯身划船',mul:2,imp:1},'上斜宽肘划船':{m:'Pull',mus:['后束','上背'],pat:'宽肘划船',mul:2,imp:.55},'坐姿俯身飞鸟':{m:'Pull',mus:['后束','上背'],pat:'肩水平外展',mul:2,imp:.4},'哑铃仰卧上拉':{m:'Pull',mus:['背阔肌','胸'],pat:'肩伸',mul:2,imp:.55},'靠腿二头弯举':{m:'Pull',mus:['二头'],pat:'肘屈',mul:2,imp:.55},
'壶铃摆动':{m:'Legs',mus:['臀','后链','核心'],pat:'髋爆发',mul:1,imp:.8},'保加利亚分腿蹲':{m:'Legs',mus:['股四头','臀','稳定'],pat:'单腿蹲',mul:2,imp:1},'原地箭步蹲':{m:'Legs',mus:['股四头','臀','稳定'],pat:'弓步',mul:2,imp:.85},'罗马尼亚硬拉':{m:'Legs',mus:['后链','臀','腘绳肌'],pat:'髋铰链',mul:2,imp:1},'平板支撑':{m:'Legs',mus:['核心'],pat:'抗伸展',mul:1,imp:.2}
};
const MAIN=['平板卧推','坐姿推肩','上斜卧推','高位下拉','上斜划船','双臂哑铃俯身划船','保加利亚分腿蹲','罗马尼亚硬拉','靠腿二头弯举'];
const $=s=>document.querySelector(s);const fmt=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:0});const fmt1=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:1});
function canon(n){return ALIAS[(n||'').trim()]||(n||'').trim()}function md(s){const [m,d]=String(s).split('.').map(Number);return new Date(YEAR,m-1,d)}function day(d){return d.toISOString().slice(0,10)}
function setp(s){s=String(s||'').replace(/×/g,'*').replace(/\s/g,'');const a=(s.match(/[\d.]+/g)||[]).map(Number);if(/kg/i.test(s))return{kg:a[0]||0,reps:a[1]||0,count:a[2]||1,sec:0};if(/s/i.test(s))return{kg:0,reps:0,count:a[1]||1,sec:a[0]||0};return{kg:0,reps:a[0]||0,count:a[1]||1,sec:0}}
function mod(items){const t=(items||[]).map(x=>canon(x.name)).join(' ');if(t.includes('篮球'))return'Basketball';if(/休息|休整/.test(t))return'Rest';const s={Push:0,Pull:0,Legs:0};(items||[]).forEach(i=>{const c=CAT[canon(i.name)];if(c)s[c.m]++});return Object.entries(s).sort((a,b)=>b[1]-a[1])[0]?.[1]?Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0]:'Other'}
function records(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return (x.records||[]).map(r=>({date:r.date,items:(r.items||[]).map(i=>({name:canon(i.name),sets:i.sets||[]}))})).sort((a,b)=>md(a.date)-md(b.date))}catch{return[]}}
function rows(rs){const out=[];rs.forEach(r=>(r.items||[]).forEach(i=>{const name=canon(i.name),c=CAT[name];if(!c)return;(i.sets||[]).forEach(raw=>{const p=setp(raw),cnt=Math.max(1,Math.round(p.count||1));for(let k=0;k<cnt;k++){const volume=(p.kg||0)*(p.reps||0)*(c.mul||1),stim=volume*(c.imp||1);out.push({date:r.date,d:md(r.date),name,m:c.m,kg:p.kg,reps:p.reps,sec:p.sec,volume,stim,e1rm:p.kg&&p.reps?p.kg*(1+p.reps/30):0,mus:c.mus,pat:c.pat})}})}));return out}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}function med(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}function sd(a){const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)*(x-m))))}
function cal(rs,rr){if(!rs.length)return[];const m={};rs.forEach(r=>m[day(md(r.date))]={date:r.date,m:mod(r.items),volume:0,stim:0,sets:0});rr.forEach(x=>{const k=day(x.d);if(m[k]){m[k].volume+=x.volume;m[k].stim+=x.stim;m[k].sets++}});const a=[],st=md(rs[0].date),en=md(rs.at(-1).date);for(let d=new Date(st);d<=en;d.setDate(d.getDate()+1)){a.push(m[day(d)]||{date:(d.getMonth()+1)+'.'+d.getDate(),m:'Blank',volume:0,stim:0,sets:0})}return a}
function analyse(){const rs=records(),rr=rows(rs),cc=cal(rs,rr),strength=rs.filter(r=>!['Basketball','Rest'].includes(mod(r.items)));const counts={Push:0,Pull:0,Legs:0,Basketball:0,Rest:0};rs.forEach(r=>counts[mod(r.items)]=(counts[mod(r.items)]||0)+1);const load={Push:0,Pull:0,Legs:0},mus={},pat={};rr.forEach(x=>{if(load[x.m]!=null)load[x.m]+=x.stim;x.mus.forEach(m=>mus[m]=(mus[m]||0)+x.stim);pat[x.pat]=(pat[x.pat]||0)+x.stim});const total=rr.reduce((s,x)=>s+x.volume,0),stim=rr.reduce((s,x)=>s+x.stim,0);const l7=cc.slice(-7),p7=cc.slice(-14,-7),l28=cc.slice(-28);const acute=l7.reduce((s,x)=>s+x.volume,0),prev=p7.reduce((s,x)=>s+x.volume,0),chronic=Math.max(1,l28.reduce((s,x)=>s+x.volume,0)/4);const acwr=acute/chronic,mono=mean(l7.map(x=>x.volume))/(sd(l7.map(x=>x.volume))||1),strain=acute*mono,trend=prev?acute/prev-1:0;const prs=MAIN.map(n=>{const by={};rr.filter(x=>x.name===n&&x.e1rm).forEach(x=>by[x.date]=Math.max(by[x.date]||0,x.e1rm));const xs=Object.entries(by).map(([date,e])=>({date,e}));if(xs.length<2)return null;const base=med(xs.slice(0,2).map(x=>x.e)),now=med(xs.slice(-2).map(x=>x.e)),best=xs.reduce((a,b)=>b.e>a.e?b:a,xs[0]);return{name:n,gain:base?now/base-1:0,bestGain:base?best.e/base-1:0,base,now,best,count:xs.length}}).filter(Boolean).sort((a,b)=>b.gain-a.gain);let risk='低',why='恢复压力低，可以正常推进。';if(acwr>1.5||mono>2.2){risk='高';why='短期负荷或训练单调性偏高，下一次不要冲 PR。'}else if(acwr>1.2||mono>1.7){risk='中';why='恢复压力中等，主项可以维持，小肌群控制总量。'}const bal=(()=>{const v=[counts.Push,counts.Pull,counts.Legs].filter(Boolean);return v.length?1-(Math.max(...v)-Math.min(...v))/Math.max(...v):0})();return{rs,rr,cc,strength,counts,load,mus,pat,total,stim,acute,prev,chronic,acwr,mono,strain,trend,prs,risk,why,bal}}
function css(){if($('#analysisCss'))return;const s=document.createElement('style');s.id='analysisCss';s.textContent='.pro-grid{display:grid;gap:12px}.pro-kpis{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pro-kpi{min-height:92px}.pro-kpi small{display:block;color:var(--muted);font-size:11px;font-weight:900}.pro-kpi b{display:block;font-size:24px;letter-spacing:-.04em}.pro-badge{display:inline-block;border-radius:999px;padding:6px 9px;background:rgba(255,255,255,.62);border:1px solid rgba(255,255,255,.76);font-size:11px;font-weight:950;color:#2e6988;margin:3px 5px 3px 0}.pro-row{display:grid;grid-template-columns:82px 1fr 56px;gap:8px;align-items:center;border-radius:16px;padding:9px;background:rgba(255,255,255,.52);border:1px solid rgba(255,255,255,.68);font-size:12px;font-weight:850;margin-bottom:8px}.pro-bar{height:10px;border-radius:999px;background:rgba(45,80,116,.10);overflow:hidden}.pro-bar i{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--a),var(--b))}.pro-note{font-size:12px;line-height:1.65;color:#53677d;font-weight:780}.pro-high{color:#b33d52}.pro-mid{color:#9a6418}.pro-low{color:#08785e}.pro-svg{width:100%;height:auto;display:block}.pro-svg text{font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}.pro-title{display:flex;justify-content:space-between;gap:10px;margin-bottom:10px}.pro-title h3{margin:0;font-size:18px}.pro-title span{font-size:11px;color:var(--muted);font-weight:900}@media(max-width:370px){.pro-kpis{grid-template-columns:1fr}.pro-row{grid-template-columns:74px 1fr 44px}}';document.head.appendChild(s)}
function svgBars(labels,vals,unit=''){const w=360,h=190,p=30,max=Math.max(1,...vals),slot=(w-2*p)/Math.max(1,labels.length),bw=slot*.55;return`<svg class="pro-svg" viewBox="0 0 ${w} ${h}">${labels.map((l,i)=>{const bh=vals[i]/max*(h-64),x=p+i*slot+slot*.22,y=h-p-bh;return`<rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="12" fill="${i%2?'#78efd0':'#40cffd'}"/><text x="${x+bw/2}" y="${y-8}" text-anchor="middle" font-size="12" fill="#112136">${fmt(vals[i])}${unit}</text><text x="${x+bw/2}" y="${h-8}" text-anchor="middle" font-size="12" fill="#708096">${l}</text>`}).join('')}</svg>`}
function svgTrend(c){const w=360,h=210,p=28,max=Math.max(1,...c.map(x=>x.volume))*1.1,slot=(w-2*p)/Math.max(1,c.length);let pts=[];const bars=c.map((x,i)=>{const bh=x.volume/max*(h-2*p),xx=p+i*slot+slot*.18;pts.push([p+i*slot+slot*.5,h-p-bh]);const fill=x.m==='Basketball'?'#bcaeff':x.m==='Rest'?'#cbd8e4':'#40cffd',op=x.m==='Rest'?.18:.48;return`<rect x="${xx}" y="${h-p-bh}" width="${Math.max(2,slot*.64)}" height="${bh}" rx="4" fill="${fill}" opacity="${op}"/>`}).join('');return`<svg class="pro-svg" viewBox="0 0 ${w} ${h}">${bars}<path d="${pts.map((q,i)=>(i?'L':'M')+q[0]+','+q[1]).join(' ')}" fill="none" stroke="#40cffd" stroke-width="4" stroke-linecap="round"/>${pts.filter((_,i)=>i%3===0||i===pts.length-1).map(q=>`<circle cx="${q[0]}" cy="${q[1]}" r="4" fill="#112136" stroke="white" stroke-width="3"/>`).join('')}<text x="${p}" y="16" font-size="11" fill="#708096">日负荷趋势</text><text x="${p}" y="${h-4}" font-size="11" fill="#708096">${c[0]?.date||''}</text><text x="${w-p}" y="${h-4}" text-anchor="end" font-size="11" fill="#708096">${c.at(-1)?.date||''}</text></svg>`}
function list(obj){const e=Object.entries(obj).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...e.map(x=>x[1]));return e.map(([k,v])=>`<div class="pro-row"><b>${k}</b><div class="pro-bar"><i style="width:${v/max*100}%"></i></div><span>${fmt(v)}</span></div>`).join('')}
function shell(){const a=$('#analysis');if(!a)return;if(a.dataset.pro==='1')return;a.dataset.pro='1';a.innerHTML=`<header class="head"><div><h1>训练分析</h1><p class="sub" id="proRange">专业分析</p></div><div class="chip" id="proScore">PRO</div></header><div class="pro-grid"><article class="glass card"><div class="kicker">PERFORMANCE REPORT</div><p class="note" id="proSummary"></p><div id="proTags"></div></article><div class="pro-kpis" id="proKpis"></div><article class="glass card"><div class="pro-title"><h3>负荷趋势</h3><span>kg·次</span></div><div id="proTrend"></div><p class="pro-note" id="proLoadNote"></p></article><article class="glass card"><div class="pro-title"><h3>模块频率</h3><span>次数</span></div><div id="proFreq"></div></article><article class="glass card"><div class="pro-title"><h3>模块刺激量</h3><span>校正后</span></div><div id="proLoad"></div></article><article class="glass card"><div class="pro-title"><h3>肌群热区</h3><span>刺激量</span></div><div id="proMuscle"></div></article><article class="glass card"><div class="pro-title"><h3>主项进步</h3><span>e1RM中位数</span></div><div id="proPrBars"></div><div id="proPrList"></div></article><div class="section-title"><h2>结论</h2><span>可执行建议</span></div><div id="proInsights"></div></div>`}
function render(){css();shell();const a=analyse();if(!a.rs.length)return;const avg=a.strength.length?a.total/a.strength.length:0,cls=a.risk==='高'?'pro-high':a.risk==='中'?'pro-mid':'pro-low';$('#proRange').textContent=`${a.rs[0].date}–${a.rs.at(-1).date} · 整合版`;$('#proScore').textContent=`恢复 ${a.risk}`;$('#proSummary').innerHTML=`当前有 <b>${a.rs.length}</b> 天记录，力量训练 <b>${a.strength.length}</b> 次，有效力量组 <b>${a.rr.length}</b> 组。分析使用训练量、刺激量、ACWR、单调性和主项 e1RM 中位数，不再只看单次最高值。`;$('#proTags').innerHTML=[`总量 ${fmt(a.total)}`,`刺激 ${fmt(a.stim)}`,`ACWR ${fmt1(a.acwr)}`,`单调性 ${fmt1(a.mono)}`,`趋势 ${a.trend>=0?'+':''}${Math.round(a.trend*100)}%`].map(x=>`<span class="pro-badge">${x}</span>`).join('');$('#proKpis').innerHTML=`<div class="glass card pro-kpi"><small>平均力量日负荷</small><b>${fmt(avg)}</b><small>kg·次/次</small></div><div class="glass card pro-kpi"><small>结构均衡度</small><b>${Math.round(a.bal*100)}</b><small>/100</small></div><div class="glass card pro-kpi"><small>最近7天负荷</small><b>${fmt(a.acute)}</b><small>kg·次</small></div><div class="glass card pro-kpi"><small>恢复压力</small><b class="${cls}">${a.risk}</b><small>ACWR ${fmt1(a.acwr)}</small></div>`;$('#proTrend').innerHTML=svgTrend(a.cc);$('#proLoadNote').innerHTML=`ACWR=${fmt1(a.acwr)}，训练单调性=${fmt1(a.mono)}，strain=${fmt(a.strain)}。${a.why}`;$('#proFreq').innerHTML=svgBars(['推','拉','腿','篮','休'],[a.counts.Push,a.counts.Pull,a.counts.Legs,a.counts.Basketball,a.counts.Rest]);$('#proLoad').innerHTML=svgBars(['推','拉','腿'],[a.load.Push,a.load.Pull,a.load.Legs])+'<p class="pro-note">刺激量按动作重要性校正，辅助动作不会和主项等权。</p>';$('#proMuscle').innerHTML=list(a.mus);const prs=a.prs.slice(0,5);$('#proPrBars').innerHTML=svgBars(prs.map(x=>x.name.slice(0,4)),prs.map(x=>Math.round(x.gain*100)),'%');$('#proPrList').innerHTML=prs.map(x=>`<div class="pro-row"><b>${x.name}</b><div><span class="pro-badge">基线 ${fmt1(x.base)}</span><span class="pro-badge">当前 ${fmt1(x.now)}</span><span class="pro-badge">峰值 ${fmt1(x.best.e)}</span><p class="pro-note">当前提升 ${Math.round(x.gain*100)}%，历史峰值提升 ${Math.round(x.bestGain*100)}%，样本 ${x.count} 次。</p></div><span>${Math.round(x.gain*100)}%</span></div>`).join('');const last=[...a.rs].reverse().find(r=>!['Basketball','Rest'].includes(mod(r.items))),seq=['Push','Pull','Legs'],lm=last?mod(last.items):'Push',next=seq[(seq.indexOf(lm)+1)%3]||'Push',top=prs[0],bias=Object.entries(a.load).sort((x,y)=>y[1]-x[1]);$('#proInsights').innerHTML=[['下一次训练',`最后力量日是 ${last?.date||'—'} 的 ${lm}。篮球和休息不推进 PPL，下一次力量建议 ${next}。${a.risk==='高'?'当前恢复压力偏高，主项维持重量，辅助动作减量。':'恢复压力可控，主项稳定完成后再末组小幅试重。'}`],['结构判断',`刺激量最高模块是 ${bias[0][0]}（${fmt(bias[0][1])}），最低是 ${bias.at(-1)[0]}（${fmt(bias.at(-1)[1])}）。如果差距继续扩大，优先补最低模块。`],['主项判断',top?`${top.name} 当前 e1RM 相比早期基线提升约 ${Math.round(top.gain*100)}%。这里用前2次中位数和最近2次中位数，避免早期过低重量夸大进步。`:'主项样本不足，继续记录后自动排行。'],['动作覆盖',`肌群刺激最高为 ${Object.entries(a.mus).sort((x,y)=>y[1]-x[1])[0]?.[0]||'—'}。如果肩肘疲劳，优先减少飞鸟/弯举等辅助堆量。`]].map(([h,p])=>`<div class="smart"><b>${h}</b><p>${p}</p></div>`).join('')}
function tick(){if($('#analysis')?.classList.contains('active'))render()}
document.addEventListener('click',e=>{if(e.target.closest('[data-tab="analysis"]')||e.target.closest('[data-action="cloudPull"]')||e.target.closest('[data-action="cloudPasswordLogin"]'))setTimeout(render,500)});
setInterval(()=>{const t=$('#planTitle');if(t&&/读取中|Loading/.test(t.textContent)&&!document.body.dataset.planWarn){document.body.dataset.planWarn='1';t.textContent='缓存异常';const p=$('#planDesc');if(p)p.textContent='当前浏览器仍在跑旧缓存。到「档案」点清理缓存并重载，或打开 ?v=39&clean=1。'}tick()},1500);
window.addEventListener('focus',()=>setTimeout(tick,120));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,80));else setTimeout(render,80);
})();
