(()=>{
'use strict';
if(window.__GYM_UPGRADE_V41__)return;window.__GYM_UPGRADE_V41__=true;
const KEY='gym-vault-v36-cloud',YEAR=2026,IMG='./images/v41/';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const PLAN={Push:{title:'Push 日',sub:'胸 / 肩 / 三头',img:'plan_push.svg',items:[['平板卧推','3 × 8–12','主项','胸 / 三头'],['坐姿推肩','3 × 8–12','主项','肩 / 三头'],['上斜卧推','3 × 8–12','上胸','上胸 / 前束'],['侧平举','3–4 × 12–15','中束','侧三角'],['过顶臂屈伸','3 × 10–12','三头','三头']]},Pull:{title:'Pull 日',sub:'背 / 后束 / 二头',img:'plan_pull.svg',items:[['高位下拉','3 × 8–12','主项','背阔肌 / 二头'],['上斜划船','3–4 × 8–12','主项','中背 / 背阔'],['双臂哑铃俯身划船','3 × 8–12','厚度','中背 / 后束'],['坐姿俯身反向飞鸟','2–3 × 12–15','后束','后束 / 上背'],['靠腿二头弯举','3 × 10–12','二头','二头']]},Legs:{title:'Legs 日',sub:'腿 / 臀 / 核心',img:'plan_legs.svg',items:[['壶铃摆动','4 × 10–12','爆发','臀 / 后链'],['保加利亚分腿蹲','3 × 8–10 × 2','单腿','股四头 / 臀'],['平板支撑肩触碰','3 × 10–15 × 2','核心','核心 / 稳定'],['地面哑铃臀桥','3 × 10–15','臀','臀 / 后链'],['平板支撑','3 × 80s','核心','核心']]}};
const ALIAS={'哑铃平板卧推':'平板卧推','哑铃坐姿推肩':'坐姿推肩','哑铃侧平举':'侧平举','臂屈伸':'过顶臂屈伸','坐姿臂屈伸':'过顶臂屈伸','俯身飞鸟':'坐姿俯身反向飞鸟','俯身反向飞鸟':'坐姿俯身反向飞鸟','俯身哑铃飞鸟':'坐姿俯身反向飞鸟','坐姿俯身飞鸟':'坐姿俯身反向飞鸟','二头弯举':'靠腿二头弯举','靠腿弯举':'靠腿二头弯举','哑铃二头弯举':'靠腿二头弯举','保加利亚蹲':'保加利亚分腿蹲','箭步蹲':'原地箭步蹲','哑铃箭步蹲':'原地箭步蹲'};
const canon=n=>ALIAS[(n||'').trim()]||(n||'').trim();
function toast(m){const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}function saveState(s){localStorage.setItem(KEY,JSON.stringify(s))}
function md(x){const [m,d]=String(x).split('.').map(Number);return new Date(YEAR,m-1,d)}function lab(d){return `${d.getMonth()+1}.${d.getDate()}`}
function mod(items){const txt=(items||[]).map(i=>canon(i.name)).join(' ');if(txt.includes('篮球'))return'Basketball';if(/休息|休整/.test(txt))return'Rest';const s={Push:0,Pull:0,Legs:0};for(const it of items||[]){for(const k of ['Push','Pull','Legs'])if(PLAN[k].items.some(x=>x[0]===canon(it.name)))s[k]++}return Object.entries(s).sort((a,b)=>b[1]-a[1])[0]?.[1]?Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0]:'Other'}
function next(){const rs=(state().records||[]).sort((a,b)=>md(a.date)-md(b.date)),last=rs.at(-1),date=last?lab(new Date(md(last.date).getTime()+86400000)):lab(new Date()),lastS=[...rs].reverse().find(r=>!['Basketball','Rest'].includes(mod(r.items))),seq=['Push','Pull','Legs'],lm=lastS?mod(lastS.items):'Legs';return{module:seq[(seq.indexOf(lm)+1)%3]||'Push',date,last:lastS}}
function lastKg(name){const rs=(state().records||[]).slice().reverse(),target=canon(name);for(const r of rs)for(const it of r.items||[])if(canon(it.name)===target){const s=(it.sets||[]).slice().reverse().find(x=>/kg/i.test(x));if(s)return (String(s).match(/[\d.]+/)||[''])[0]}return''}
function css(){if($('#upgradeStyle'))return;const s=document.createElement('style');s.id='upgradeStyle';s.textContent='.plan-img{width:100%;display:block;border-radius:24px;border:1px solid rgba(255,255,255,.82);background:rgba(255,255,255,.72);box-shadow:0 18px 40px rgba(47,111,155,.14);margin:10px 0 14px}.u-card{padding:14px;margin-bottom:12px;border-radius:28px}.u-name{font-size:20px;font-weight:1000;letter-spacing:-.04em}.u-meta{font-size:12px;color:#5b7188;font-weight:850;margin-top:4px}.u-sets{display:grid;gap:8px;margin-top:10px}.u-set{display:grid;grid-template-columns:42px 52px 1fr 1fr;gap:7px;align-items:center;border-radius:18px;padding:8px;background:rgba(255,255,255,.55);border:1px solid rgba(255,255,255,.72)}.u-set.done{background:linear-gradient(110deg,rgba(109,242,216,.34),rgba(255,255,255,.64));border-color:rgba(79,194,169,.36)}.u-check{width:38px;height:38px;border-radius:14px;background:rgba(255,255,255,.8);font-weight:1000}.u-set.done .u-check{background:linear-gradient(135deg,var(--a),var(--b));color:#fff}.u-set input{width:100%;height:40px;border-radius:15px;border:1px solid rgba(47,89,128,.12);background:rgba(255,255,255,.8);padding:0 10px;font-weight:950}.u-cue{border-radius:16px;background:rgba(255,255,255,.55);border:1px solid rgba(255,255,255,.72);padding:9px;margin-top:8px;font-size:12px;line-height:1.45;font-weight:780;color:#40566f}';document.head.appendChild(s)}
function render(){const screen=$('#check');if(!screen||!screen.classList.contains('active'))return;css();const n=next(),p=PLAN[n.module],list=$('#planList');if(!p||!list)return;$('#planTitle').innerHTML=p.title.replace(' 日','')+'<span class="hero-title-cn">日</span>';$('#planDesc').textContent=`计划日期 ${n.date} · 上次力量 ${n.last?.date||'—'}，篮球/休息不推进三分化。`;$('#todayLine').textContent=p.sub+' · 最新三分化计划';$('#datePill').textContent=n.date;$('#heroTags').innerHTML=`<span>新版计划</span><span>动作图示</span><span>默认12次</span><span>${p.sub}</span>`;list.innerHTML=`<img class="plan-img" src="${IMG+p.img}" alt="${p.title}">`+p.items.map((ex,i)=>{let sets=Number((ex[1].match(/^\d+/)||[3])[0]);if(ex[0]==='侧平举'||ex[0]==='上斜划船')sets=4;const isTime=ex[0]==='平板支撑',noKg=ex[0]==='平板支撑'||ex[0]==='平板支撑肩触碰';const kg=noKg?'':lastKg(ex[0]);return`<article class="glass card u-card" data-u-ex="${i}"><div class="ex-top"><div><div class="u-name">${ex[0]}</div><div class="u-meta">${ex[3]} · ${ex[1]}</div></div><span class="pill">${ex[2]}</span></div><div class="u-cue">动作标准优先；稳定完成目标次数后，下一次再小幅加重。</div><div class="u-sets">${Array.from({length:sets},(_,j)=>`<div class="u-set" data-ex="${i}"><button class="u-check" type="button">✓</button><b>第${j+1}组</b><input class="u-kg" value="${kg}" ${noKg?'disabled':''} placeholder="${noKg?'—':'kg'}"><input class="u-reps" value="${isTime?'80':'12'}" placeholder="${isTime?'秒':'次数'}"></div>`).join('')}</div></article>`}).join('');count()}
function count(){const all=$$('.u-set'),done=all.filter(x=>x.classList.contains('done')).length;if($('#setCounter'))$('#setCounter').textContent=`${done}/${all.length} 组`;if($('#ring'))$('#ring').style.setProperty('--p',all.length?Math.round(done/all.length*100):0);if($('#progressText'))$('#progressText').textContent=(all.length?Math.round(done/all.length*100):0)+'%'}
function build(){const n=next(),p=PLAN[n.module],items=[];p.items.forEach((ex,i)=>{const sets=[];$$(`.u-set[data-ex="${i}"]`).forEach(row=>{if(!row.classList.contains('done'))return;const kg=$('.u-kg',row)?.value,reps=$('.u-reps',row)?.value||'12';if(ex[0]==='平板支撑')sets.push(`${reps}s`);else if(ex[0]==='平板支撑肩触碰')sets.push(`${reps}`);else sets.push(`${kg||0}kg*${reps}`)});if(sets.length)items.push({name:ex[0],sets})});return{date:n.date,items,module:n.module}}
function save(){const r=build();if(!r.items.length){toast('至少勾选一组再保存。');return}const st=state(),rs=(st.records||[]).filter(x=>x.date!==r.date);rs.push({date:r.date,items:r.items});rs.sort((a,b)=>md(a.date)-md(b.date));st.records=rs;saveState(st);toast(`已保存 ${r.date} ${r.module}。需要云端备份时到档案点上传本机档案。`);render()}
function basketball(){const n=next(),st=state(),rs=(st.records||[]).filter(x=>x.date!==n.date);rs.push({date:n.date,items:[{name:'篮球',sets:[]}]});rs.sort((a,b)=>md(a.date)-md(b.date));st.records=rs;saveState(st);toast(`已记录 ${n.date} 篮球/有氧。`);render()}
document.addEventListener('click',e=>{if(e.target.closest('.u-check')){e.target.closest('.u-set').classList.toggle('done');count();return}const a=e.target.closest('[data-action]')?.dataset.action;if(a==='save'){e.preventDefault();e.stopImmediatePropagation();save()}if(a==='reset'){e.preventDefault();e.stopImmediatePropagation();render();toast('已重置今日。')}if(a==='basketball'){e.preventDefault();e.stopImmediatePropagation();basketball()}},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-tab="check"]'))setTimeout(render,80)});setInterval(render,1500);window.addEventListener('focus',()=>setTimeout(render,80));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,100));else setTimeout(render,100);
})();