(()=>{'use strict';
const VERSION='V20',KEY='gym-vault-v20';
const RAW="5.16\n哑铃平板卧推\n10kg*12*2\n12.5kg*12*2\n标准俯卧撑\n15*3\n哑铃坐姿推肩\n10kg*8*2\n8kg*10*2\n哑铃侧平举\n3kg*15*3\n哑铃过顶臂屈伸\n6kg*10*3\n窄距俯卧撑\n8*2\n\n5.17\n高位下拉\n11kg*12\n18kg*12*2\n单臂哑铃划船\n10kg*12\n7.5kg*12*2\n双哑铃上斜划船\n7.5kg*12*3\n俯身反向飞鸟\n3kg*15*3\n坐姿靠腿二头弯举\n10kg*12\n12.5kg*12*2\n\n5.18\n壶铃摆动\n10kg*20*4\n保加利亚分腿蹲\n8kg*12*2\n10kg*12\n原地箭步蹲\n8kg*12\n10kg*12*2\n哑铃罗马尼亚硬拉\n10kg*12\n12.5kg*12*2\n平板支撑\n70s*3\n\n5.19\n🏀\n\n5.20\n平板卧推\n12.5kg*12*3\n坐姿推肩\n10kg*12*3\n侧平举\n4kg*15*3\n坐姿臂屈伸\n6kg*12\n8kg*12*3\n俯卧撑\n15*3\n上斜卧推\n12.5kg*12*3\n\n5.21\n哑铃仰卧上拉\n10kg*12*3\n上斜划船\n8kg*12*3\n单臂哑铃划船\n10kg*12*3\n俯身反向飞鸟\n3kg*15*3\n坐姿靠腿二头弯举\n12.5kg*12*3\n\n5.22\n🏀\n\n5.23\n壶铃摆动\n10kg*15*4\n保加利亚分腿蹲\n10kg*12*3\n哑铃箭步蹲\n10kg*12*3\n罗马尼亚硬拉\n10kg*12\n12.5kg*12*2\n平板支撑\n120s\n75s\n\n5.24\n平板卧推\n12.5kg*12*4\n哑铃推肩\n10kg*12*4\n上斜卧推\n12.5kg*12\n10kg*12*3\n哑铃侧平举\n3kg*15*4\n坐姿臂屈伸\n7.5kg*12\n8kg*12*3\n\n5.25\n哑铃仰卧上拉\n8kg*12*4\n上斜划船\n8kg*12*4\n单臂哑铃划船\n8kg*12*4\n俯身反向飞鸟\n2kg*15*2\n3kg*12*2\n\n5.26\n壶铃摆动\n10kg*12*4\n保加利亚分腿蹲\n10kg*12*3\n哑铃箭步蹲\n10kg*12*3\n罗马尼亚硬拉\n12.5kg*12*3\n平板支撑\n75s*3\n\n5.27\n🏀\n\n5.28\n平板卧推\n12.5kg*12*3\n15kg*12\n坐姿推肩\n12.5kg*12*3\n上斜卧推\n12.5kg*12*3\n侧平举\n4kg*15*4\n坐姿臂屈伸\n10kg*12*3\n\n5.29\n摆\n\n5.30\n高位下拉\n15kg*12\n20kg*12*3\n上斜划船\n10kg*12*3\n单臂划船\n10kg*12*3\n上斜宽肘划船\n4kg*15\n5kg*15*2\n二头弯举\n12.5kg*12*2\n15kg*12\n\n5.31\n壶铃摆动\n10kg*12*3\n保加利亚蹲\n10kg*12*3\n哑铃箭步蹲\n12.5kg*12*3\n罗马尼亚硬拉\n15kg*12*2\n17.5kg*12\n平板支撑\n70s*2\n\n6.1\n平板卧推\n15kg*12*3\n坐姿推肩\n12.5kg*12*3\n上斜卧推\n12.5kg*12*3\n哑铃侧平举\n4kg*15*3\n坐姿臂屈伸\n10kg*12*2\n12.5kg*12\n\n6.2\n高位下拉\n20kg*12\n25kg*12\n30kg*12\n上斜划船\n10kg*12*3\n单臂划船\n10kg*12*3\n上斜宽肘划船\n5kg*12\n6kg*12*2\n靠腿弯举\n12.5kg*15*3\n\n6.3\n🏀\n\n6.4\n壶铃摆动\n10kg*15*4\n保加利亚蹲\n10kg*12*3\n哑铃箭步蹲\n15kg*12*3\n罗马尼亚硬拉\n15kg*12\n\n6.5\n平板卧推\n15kg*12*3\n坐姿推肩\n12.5kg*12*3\n上斜卧推\n12.5kg*12*2\n15kg*8\n侧平举\n4kg*15*4\n过顶臂屈伸\n12.5kg*12\n\n6.6\n高位下拉\n25kg*12*3\n30kg*12\n上斜划船\n12.5kg*12*3\n单臂划船\n10kg*12*3\n上斜宽肘划船\n6kg*12*3\n靠腿弯举\n15kg*12*3";
const rules=[['哑铃平板卧推','平板卧推'],['哑铃推肩','坐姿推肩'],['哑铃坐姿推肩','坐姿推肩'],['哑铃侧平举','侧平举'],['坐姿臂屈伸','过顶臂屈伸'],['哑铃过顶臂屈伸','过顶臂屈伸'],['双哑铃上斜划船','上斜划船'],['单臂划船','单臂哑铃划船'],['二头弯举','靠腿二头弯举'],['靠腿弯举','靠腿二头弯举'],['坐姿靠腿二头弯举','靠腿二头弯举'],['保加利亚蹲','保加利亚分腿蹲'],['哑铃箭步蹲','原地箭步蹲'],['哑铃罗马尼亚硬拉','罗马尼亚硬拉'],['罗马尼亚硬拉','罗马尼亚硬拉'],['俯身反向飞鸟','上斜胸托反向飞鸟'],['摆','休整'],['🏀','篮球']];
const planLib={Push:[['平板卧推','主项','默认 12 次','肩胛后缩下沉，肘部约45°；下放稳，推起别耸肩。',[['15kg','12'],['15kg','12'],['15kg','12']]],['坐姿推肩','肩部主项','默认 12 次','核心收紧，手肘略在身体前侧，不靠后仰借力。',[['12.5kg','12'],['12.5kg','12'],['12.5kg','12']]],['上斜卧推','上胸','默认 12 次','凳子别太陡，肩胛稳定，推起轨迹略向上。',[['12.5kg','12'],['12.5kg','12'],['12.5kg','12']]],['侧平举','中束','默认 12 次','手肘微弯，肩带动上抬，不要耸肩甩重量。',[['4kg','12'],['4kg','12'],['4kg','12'],['4kg','12']]],['过顶臂屈伸','三头','默认 12 次','肘关节固定，慢下快起，避免腰椎过伸。',[['12.5kg','12'],['12.5kg','12'],['12.5kg','12']]]],Pull:[['高位下拉','主项','默认 12 次','先沉肩再拉，肘向下走，别用身体后仰硬拽。',[['25kg','12'],['25kg','12'],['25kg','12']]],['上斜划船','厚度','默认 12 次','胸贴凳，肩胛向后收，顶峰停一瞬。',[['12.5kg','12'],['12.5kg','12'],['12.5kg','12'],['12.5kg','12']]],['双臂哑铃俯身划船','背阔/厚度','默认 12 次','髋向后坐、背保持中立，两侧哑铃同时向髋部拉。',[['10kg','12'],['10kg','12'],['10kg','12']]],['上斜胸托反向飞鸟','后束/上背','默认 12 次','胸托凳面，手臂微弯打开，顶峰停顿，不借腰摆。',[['3kg','12'],['3kg','12'],['3kg','12']]],['靠腿二头弯举','二头','默认 12 次','上臂贴腿固定，顶峰挤压，不要借摆。',[['15kg','12'],['15kg','12'],['15kg','12']]]],Legs:[['壶铃摆动','髋伸展','默认 12 次','髋关节铰链发力，不是蹲起；靠臀腿把壶铃弹出去。',[['10kg','12'],['10kg','12'],['10kg','12'],['10kg','12']]],['保加利亚分腿蹲','单侧腿','默认 12 次 / 侧','每侧都做；前脚踩稳，身体略前倾，膝盖跟脚尖同向。',[['10kg','12'],['10kg','12'],['10kg','12']]],['原地箭步蹲','单侧腿','默认 12 次 / 侧','每侧都做；步幅稍大，下落垂直，前腿发力站起。',[['15kg','12'],['15kg','12'],['15kg','12']]],['罗马尼亚硬拉','后链','默认 12 次','髋向后推，背保持中立，感受腘绳肌被拉长。',[['15kg','12'],['15kg','12'],['15kg','12']]],['平板支撑','核心','默认 75s','肋骨下压，臀部微收，别塌腰。',[['','75s'],['','75s'],['','75s']]]]};
const cueMap={
'平板卧推':[['肩胛','后缩下沉，不要耸肩。'],['肘角','约45°，别打开太大。'],['节奏','下放慢，推起稳，不弹胸。']],
'坐姿推肩':[['躯干','核心收紧，腰不要反弓。'],['轨迹','哑铃略在耳旁前侧垂直上推。'],['肩部','不耸肩，顶端别硬锁死。']],
'上斜卧推':[['角度','凳面约30–45°，主打上胸。'],['肩胛','全程稳定贴住凳面。'],['发力','推向上胸上方，别用腰顶。']],
'侧平举':[['重量','宁轻不甩，先找中束发力。'],['高度','抬到肩高附近即可。'],['斜方','肩放松，避免耸肩代偿。']],
'过顶臂屈伸':[['肘位','肘尽量固定，不外张太多。'],['下放','有拉伸感即可，别过度压肩。'],['发力','三头伸展，不靠腰反弓。']],
'高位下拉':[['启动','先沉肩，再让肘向下走。'],['终点','拉到上胸附近即可。'],['躯干','可微后仰，不能大幅借力。']],
'上斜划船':[['胸托','胸贴凳，减少腰部借力。'],['肩胛','先收肩胛，再拉肘。'],['高度','拉到身体旁，不要耸肩拉太高。']],
'双臂哑铃俯身划船':[['髋位','髋向后坐，背保持中立。'],['路线','肘向后拉到髋旁。'],['控制','别甩重量，顶峰停一瞬。']],
'上斜胸托反向飞鸟':[['重量','轻重量优先，动作打开。'],['路线','手臂微弯向两侧展开。'],['感觉','后束发力，不要斜方耸起来。']],
'靠腿二头弯举':[['固定','上臂贴腿，减少摆动。'],['顶峰','顶端挤压二头。'],['下放','慢放，别让哑铃自由落下。']],
'壶铃摆动':[['模式','髋铰链，不是深蹲。'],['动力','髋和臀把壶铃弹出，手只是挂钩。'],['高度','胸口附近即可，不用抬过高。']],
'保加利亚分腿蹲':[['站距','前脚踩稳，后脚只辅助。'],['膝盖','朝脚尖方向走，不内扣。'],['重心','略前倾，主要靠前腿发力。']],
'原地箭步蹲':[['步距','自然稳定，前脚全脚掌踩实。'],['下放','躯干稳定，别左右晃。'],['发力','前腿蹬地站起，不靠后腿弹。']],
'罗马尼亚硬拉':[['髋铰链','髋向后推，膝盖微屈。'],['背部','全程中立，不圆背。'],['哑铃','贴近腿下放，感受腘绳肌拉伸。']],
'平板支撑':[['线条','头、背、髋保持一条线。'],['核心','肋骨下压，臀部微收。'],['呼吸','正常呼吸，别憋气硬撑。']]
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(t){const n=$('#toast');n.textContent=t;n.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>n.classList.remove('show'),1800)}
function canon(n){n=(n||'').trim();for(const [a,b] of rules) if(n===a)return b;return n}
function parseRaw(raw){return raw.trim().split(/\n\s*\n/).map(block=>{const lines=block.split('\n').map(x=>x.trim()).filter(Boolean),date=lines.shift(),items=[];for(let i=0;i<lines.length;i++){if(!/^\d/.test(lines[i])||lines[i]==='🏀'){const name=canon(lines[i]),sets=[];while(lines[i+1]&&/^(\d|[\d.]+kg|[\d.]+s)/.test(lines[i+1]))sets.push(lines[++i].replaceAll('×','*'));items.push({name,sets})}}return {date,items}}).filter(r=>r.date)}
function mdDate(md){const d=md.split('.').map(Number);return new Date(new Date().getFullYear(),d[0]-1,d[1])}
function md(d){return (d.getMonth()+1)+'.'+d.getDate()}
function normalize(recs){const m=new Map();recs.forEach(r=>m.set(r.date,{date:r.date,items:(r.items||[]).map(i=>({name:canon(i.name),sets:(i.sets||[]).map(s=>String(s).replaceAll('×','*'))}))}));return [...m.values()].sort((a,b)=>mdDate(a.date)-mdDate(b.date))}
function merge(a,b){const m=new Map();normalize(b).forEach(r=>m.set(r.date,r));normalize(a).forEach(r=>m.set(r.date,r));return [...m.values()].sort((x,y)=>mdDate(x.date)-mdDate(y.date))}
function cat(r){const n=(r.items||[]).map(i=>i.name).join(' ');if(n.includes('篮球'))return'篮球';if(n.includes('休整'))return'休整';if(/卧推|推肩|侧平举|臂屈伸|俯卧撑/.test(n))return'Push';if(/下拉|划船|弯举|上拉|飞鸟/.test(n))return'Pull';if(/摆动|蹲|硬拉|支撑|箭步/.test(n))return'Legs';return'休整'}
function nextType(t){return t==='Push'?'Pull':t==='Pull'?'Legs':'Push'}
function setParts(s){s=String(s).replace(/[–—]/g,'-');const kg=(s.match(/([\d.]+)\s*kg/i)||[])[1];const nums=[...s.matchAll(/([\d.]+)(?:-([\d.]+))?/g)].map(m=>m[2]?(+m[1]+ +m[2])/2:+m[1]);return {kg:kg?+kg:0,reps:kg?(nums[1]||0):(nums[0]||0),count:kg?(nums[2]||1):(nums[1]||1)}}
function factor(name){return ['平板卧推','上斜卧推','坐姿推肩','侧平举','上斜划船','双臂哑铃俯身划船','单臂哑铃划船','罗马尼亚硬拉','原地箭步蹲','保加利亚分腿蹲','靠腿二头弯举'].includes(name)?2:1}
function volume(r){return ['篮球','休整'].includes(cat(r))?0:Math.round((r.items||[]).reduce((a,i)=>a+(i.sets||[]).reduce((b,s)=>{const p=setParts(s);return b+p.kg*p.reps*p.count*factor(i.name)},0),0))}
function latestStrength(){return state.records.filter(r=>!['篮球','休整'].includes(cat(r))).at(-1)||null}
function bestFor(name){let best=null;state.records.forEach(r=>(r.items||[]).filter(i=>i.name===name).forEach(i=>(i.sets||[]).forEach(s=>{const p=setParts(s);if(p.kg&&(!best||p.kg>best.kg||(p.kg===best.kg&&p.reps>best.reps)))best={...p,date:r.date}})));return best}
function fmtKg(x){return x?String(+x.toFixed(1)).replace('.0','')+'kg':''}
function adaptive(ex){const b=bestFor(ex.name);if(!b||['壶铃摆动','平板支撑','侧平举','上斜胸托反向飞鸟'].includes(ex.name))return ex.sets;const stable=b.reps>=12,jump=b.kg>=25?5:b.kg>=7.5?2.5:1,target='12';let sets=ex.sets.map(s=>[fmtKg(b.kg),s[1]||target]);if(stable&&sets.length>=3)sets=sets.map((s,i)=>i===sets.length-1?[fmtKg(b.kg+jump),target]:[fmtKg(b.kg),target]);return sets}
function planContext(){const last=latestStrength(),type=last?nextType(cat(last)):'Push';let date=md(new Date());if(last&&mdDate(last.date)>=mdDate(date)){const d=mdDate(last.date);d.setDate(d.getDate()+1);date=md(d)}const label={Push:'Push 日',Pull:'Pull 日',Legs:'Legs 日'}[type],line={Push:'胸肩三头',Pull:'背二头',Legs:'臀腿核心'}[type];const exercises=planLib[type].map(x=>{const ex={name:x[0],kind:x[1],target:x[2],tip:x[3],sets:x[4]};ex.sets=adaptive(ex);ex.rec=ex.sets.map(s=>s[0]?s[0]+'×'+s[1]:s[1]).join(' / ');return ex});return {type,date,label,line,last,exercises}}
function defaultState(){return {version:VERSION,records:normalize(parseRaw(RAW)),checkins:{},timers:{work:{run:false,start:0,elapsed:0},rest:{dur:90,run:false,end:0}}}}
let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')||defaultState();state.records=merge(state.records||[],parseRaw(RAW));state.checkins=state.checkins||{};state.timers=state.timers||defaultState().timers}catch{state=defaultState()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function checkin(){const ctx=planContext(),key=ctx.date+'-'+ctx.type;state.active=key;if(!state.checkins[key])state.checkins[key]={date:ctx.date,type:ctx.type,exercises:ctx.exercises.map(e=>({name:e.name,sets:e.sets.map((s,i)=>({weight:s[0],reps:s[1],done:false,id:i}))}))};return {ctx,c:state.checkins[key]}}
const imageMap={'平板卧推':'./images/push_1.jpg','坐姿推肩':'./images/push_2.jpg','上斜卧推':'./images/push_3.jpg','侧平举':'./images/push_4.jpg','过顶臂屈伸':'./images/push_5.jpg','高位下拉':'./images/pull_1.jpg','上斜划船':'./images/pull_2.jpg','双臂哑铃俯身划船':'./images/pull_3.jpg','上斜胸托反向飞鸟':'./images/pull_4.jpg','靠腿二头弯举':'./images/pull_5.jpg','壶铃摆动':'./images/legs_1.jpg','保加利亚分腿蹲':'./images/legs_2.jpg','原地箭步蹲':'./images/legs_3.jpg','罗马尼亚硬拉':'./images/legs_4.jpg','平板支撑':'./images/legs_5.jpg'};
function isPlank(name){return name==='平板支撑'}
function weightDisplay(v,name){if(isPlank(name))return '';return String(v||'').replace(/kg/ig,'').trim()}
function repsDisplay(v,name){if(isPlank(name))return String(v||'').replace(/s$/i,'').trim();return v}
function renderPlan(){const {ctx,c}=checkin();$('#planTitle').textContent=ctx.label;$('#todayLine').textContent=ctx.line+' · 动态科学计划';$('#datePill').textContent=ctx.date;$('#planDesc').textContent=ctx.last?`计划日期 ${ctx.date} · 上次力量 ${ctx.last.date}，按你的最新三分化模板递进。`:`计划日期 ${ctx.date} · 从 Push 开始。`;$('#heroTags').innerHTML='<span>完整档案</span><span>动作图示</span><span>默认 12 次</span>';$('#planList').innerHTML=ctx.exercises.map((e,i)=>`<article class="glass card exercise" data-ex="${i}"><div class="ex-top"><div><div class="ex-name">${e.name}</div><div class="target">${e.target}</div></div><div class="pill">${e.kind}</div></div><div class="visual"><img src="${imageMap[e.name]||''}" alt="${e.name}"><div class="coach-grid">${(cueMap[e.name]||[]).map(c=>`<div class="cue"><b>${c[0]}</b><span>${c[1]}</span></div>`).join('')}</div></div><div class="set-head"><span></span><span>组数</span><span>${isPlank(e.name)?'负荷':''} ${isPlank(e.name)?'':'kg'}</span><span>${isPlank(e.name)?'时间 s':'次数'}</span></div><div class="set-list">${c.exercises[i].sets.map((s,j)=>`<div class="set-row ${s.done?'done':''}" data-ex="${i}" data-set="${j}"><button class="check" data-action="toggle">${s.done?'✓':''}</button><div>第${j+1}组</div><div class="field"><input data-field="weight" value="${weightDisplay(s.weight,e.name)}" placeholder="${isPlank(e.name)?'—':'重量'}"><span class="unit">${isPlank(e.name)?'':'kg'}</span></div><div class="field"><input data-field="reps" value="${repsDisplay(s.reps,e.name)}" placeholder="${isPlank(e.name)?'时间':'次数'}"><span class="unit">${isPlank(e.name)?'s':''}</span></div></div>`).join('')}</div><p class="tip">${e.tip}</p><div class="bar"><i></i></div></article>`).join('');updateProgress()}
function updateProgress(){const {c}=checkin();let d=0,t=0;c.exercises.forEach(e=>e.sets.forEach(s=>{t++;if(s.done)d++}));const p=t?Math.round(d/t*100):0;$('#progressText').textContent=p+'%';$('#ring').style.setProperty('--p',p);$('#setCounter').textContent=`${d}/${t} 组`;$$('.exercise').forEach((el,i)=>{const ex=c.exercises[i],done=ex.sets.filter(s=>s.done).length;el.querySelector('.bar i').style.width=(done/ex.sets.length*100)+'%'});save()}
function buildAnalysis(){const rec=state.records.slice().sort((a,b)=>mdDate(a.date)-mdDate(b.date)),str=rec.filter(r=>!['篮球','休整'].includes(cat(r)));const counts={Push:0,Pull:0,Legs:0,篮球:0,休整:0},loads={Push:0,Pull:0,Legs:0},setsBy={Push:0,Pull:0,Legs:0};rec.forEach(r=>{const c=cat(r);counts[c]=(counts[c]||0)+1;if(loads[c]!=null){loads[c]+=volume(r);setsBy[c]+=(r.items||[]).reduce((n,i)=>n+(i.sets||[]).length,0)}});const vols=str.map(r=>({label:r.date.replace('.', '/'),value:volume(r)}));const total=vols.reduce((a,x)=>a+x.value,0),avg=str.length?Math.round(total/str.length):0;const first3=str.slice(0,3),last3=str.slice(-3);const fa=first3.reduce((a,r)=>a+volume(r),0)/Math.max(1,first3.length),la=last3.reduce((a,r)=>a+volume(r),0)/Math.max(1,last3.length),trend=fa?(la/fa-1)*100:0;const gapDays=[];for(let i=1;i<str.length;i++)gapDays.push((mdDate(str[i].date)-mdDate(str[i-1].date))/86400000);const avgGap=gapDays.length?gapDays.reduce((a,b)=>a+b,0)/gapDays.length:0;const targets=['平板卧推','高位下拉','坐姿推肩','上斜卧推','上斜划船','罗马尼亚硬拉','原地箭步蹲','靠腿二头弯举'];const prs=targets.map(name=>{let best=null,first=null;rec.forEach(r=>(r.items||[]).filter(i=>i.name===name).forEach(i=>(i.sets||[]).forEach(s=>{const p=setParts(s),e=p.kg&&p.reps?p.kg*(1+p.reps/30):0;if(e){if(first==null)first=e;if(!best||e>best.e)best={name,date:r.date,kg:p.kg,reps:p.reps,e,gain:first?(e/first-1)*100:0}}})));return best}).filter(Boolean).sort((a,b)=>b.gain-a.gain);const moduleDiff=Math.max(counts.Push,counts.Pull,counts.Legs)-Math.min(counts.Push,counts.Pull,counts.Legs);let profile='标准进步型';if(moduleDiff<=1&&trend>=8)profile='均衡增长型';else if(trend>20)profile='加速进步型';else if(trend<0)profile='波动调整型';const consistency=Math.max(0,100-Math.round(avgGap*12));const score=Math.min(100,Math.round(str.length*2+Math.max(0,18-moduleDiff*5)+Math.max(0,20+trend/2)+consistency*0.25));return {rec,str,counts,loads,setsBy,vols,total,avg,trend,prs,profile,avgGap,consistency,score,moduleDiff}}
function pct(v){return isFinite(v)?(v>0?'+':'')+Math.round(v)+'%':'—'}
function svgLine(data){if(!data.length)return'';const w=320,h=150,p=24,max=Math.max(...data.map(x=>x.value),1),step=(w-p*2)/Math.max(1,data.length-1),xy=data.map((d,i)=>[p+i*step,p+(h-p*2)*(1-d.value/max),d]);return `<svg class="svg" viewBox="0 0 ${w} ${h}"><path d="M${p},${h-p} ${xy.map(q=>`L${q[0]},${q[1]}`).join(' ')} L${xy.at(-1)[0]},${h-p}Z" fill="rgba(88,208,255,.16)"/><path d="${xy.map((q,i)=>`${i?'L':'M'}${q[0]},${q[1]}`).join(' ')}" fill="none" stroke="#5ed7ef" stroke-width="4" stroke-linecap="round"/>${xy.map(q=>`<circle cx="${q[0]}" cy="${q[1]}" r="4" fill="#15324a" stroke="#fff" stroke-width="2"/>`).join('')}${xy.map((q,i)=>i===0||i===xy.length-1||i%Math.ceil(xy.length/4)===0?`<text x="${q[0]}" y="${h-6}" font-size="10" text-anchor="middle" fill="#718096">${q[2].label}</text>`:'').join('')}</svg>`}
function svgBars(labels,values){const w=320,h=150,p=24,max=Math.max(...values,1),gap=(w-p*2)/labels.length;return `<svg class="svg" viewBox="0 0 ${w} ${h}">${labels.map((l,i)=>{const bw=Math.min(42,gap*.58),x=p+i*gap+(gap-bw)/2,bh=(h-p*2)*(values[i]/max),y=h-p-bh;return `<rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="14" fill="${['#58d0ff','#78efd0','#b8b1ff','#91b6ff'][i%4]}"/><text x="${x+bw/2}" y="${y-6}" font-size="10" text-anchor="middle">${Math.round(values[i])}</text><text x="${x+bw/2}" y="${h-6}" font-size="10" text-anchor="middle" fill="#718096">${l}</text>`}).join('')}</svg>`}
function renderAnalysis(){const a=buildAnalysis();$('#score').textContent='训练成熟度 '+a.score;$('#range').textContent=a.rec.length?`${a.rec[0].date}–${a.rec.at(-1).date}`:'—';$('#summary').textContent=`完整档案 ${a.rec.length} 天记录中，力量训练 ${a.str.length} 次，已基于从第一天到最新一天的全部数据做动态分析。总校正训练量约 ${Math.round(a.total).toLocaleString()} kg·次，近端训练量趋势 ${pct(a.trend)}。`;$('#pills').innerHTML=[`画像 ${a.profile}`,`均次 ${a.avg.toLocaleString()}`,`PR ${a.prs.length} 项`,`平均间隔 ${a.avgGap?a.avgGap.toFixed(1):0} 天`].map(x=>`<span>${x}</span>`).join('');$('#stats').innerHTML=[[a.total,'校正总训练量','双哑铃动作自动 ×2 校正'],[a.str.length,'力量训练日','从第一天累计到最新一天'],[a.consistency,'连续性指数','基于训练间隔计算'],[pct(a.trend),'近端训练量趋势','最近 3 次 vs 最早 3 次'],[a.counts.篮球,'篮球 / 有氧日','不推进力量模块顺序'],[a.moduleDiff,'推拉腿偏差','越小表示越均衡']].map(x=>`<div class="metric glass"><b>${typeof x[0]==='number'&&!(String(x[0]).includes('%'))?Math.round(x[0]).toLocaleString():x[0]}</b><span>${x[1]}<br>${x[2]}</span></div>`).join('');$('#volChart').innerHTML=svgLine(a.vols);$('#freqChart').innerHTML=svgBars(['推','拉','腿','篮'],[a.counts.Push,a.counts.Pull,a.counts.Legs,a.counts.篮球]);$('#loadChart').innerHTML=svgBars(['推','拉','腿'],[a.loads.Push,a.loads.Pull,a.loads.Legs]);$('#prChart').innerHTML=svgBars(a.prs.slice(0,4).map(x=>x.name.slice(0,4)),a.prs.slice(0,4).map(x=>x.gain));const best=a.prs[0];const weak=[['Push',a.counts.Push],['Pull',a.counts.Pull],['Legs',a.counts.Legs]].sort((x,y)=>x[1]-y[1])[0];const zh={Push:'推',Pull:'拉',Legs:'腿'};$('#insights').innerHTML=[`【训练画像】根据完整档案，你目前更接近“${a.profile}”。这说明你不是盲目冲重量，而是在有一定稳定性的基础上逐步推进。`, `【结构判断】当前推/拉/腿次数分别为 ${a.counts.Push}/${a.counts.Pull}/${a.counts.Legs}。${a.moduleDiff<=1?'整体较均衡。':`相对偏少的是 ${zh[weak[0]]} 模块，后续应优先保证它按时出现。`}`, best?`【动作进步】目前进步最明显的主项是 ${best.name}，估算 e1RM 相比首次记录提升约 ${Math.round(best.gain)}%，最佳记录出现在 ${best.date}。`:'【动作进步】继续累计记录后，将自动生成主项 PR 排行。', `【递进建议】主项维持“稳定完成 12 次后，再在末组试重”的策略；辅助动作先保证动作质量和停顿控制，再小步进重。`].map((x,i)=>`<div class="smart"><b>${['训练画像','结构平衡','PR 判断','递进策略'][i]}</b><p>${x}</p></div>`).join('')}
function renderArchive(){ $('#archiveCount').textContent=state.records.length+' 天';$('#archiveList').innerHTML=state.records.slice().reverse().map(r=>`<div class="archive-day"><h3>${r.date}</h3>${(r.items||[]).map(i=>`<div class="archive-item"><b>${i.name}</b><p>${(i.sets||[]).join(' / ')}</p></div>`).join('')}</div>`).join('')}
function recordFromCheckin(){const {c}=checkin();return {date:c.date,items:c.exercises.map(e=>({name:e.name,sets:e.sets.filter(s=>s.done).map(s=>{const w=weightDisplay(s.weight,e.name);const r=repsDisplay(s.reps,e.name);return isPlank(e.name)?`${r}s`:(w?`${w}kg*${r}`:`${r}`)} )})).filter(i=>i.sets.length)}}
async function notifyRestEnd(){try{navigator.vibrate?.([200,80,200]);if(Notification?.permission==='granted'){const reg=await navigator.serviceWorker.getRegistration();if(reg&&reg.showNotification){reg.showNotification('组间休息结束',{body:'可以开始下一组了',icon:'./icon.svg',badge:'./icon.svg',tag:'rest-end'})}else{new Notification('组间休息结束',{body:'可以开始下一组了'})}}}catch{}}
function renderTimer(){const t=state.timers,now=Date.now(),work=Math.floor(((t.work.elapsed||0)+(t.work.run?now-t.work.start:0))/1000),rest=t.rest.run?Math.max(0,Math.ceil((t.rest.end-now)/1000)):t.rest.dur;$('#workTime').textContent=time(work);$('#timerChip').textContent=t.work.run?'训练中':'未开始';$('#restTime').textContent=restTime(rest);$('#restState').textContent=t.rest.run?'休息中':'已设定 '+t.rest.dur+' 秒';$('#restMeter').style.width=(t.rest.dur?Math.min(100,(1-rest/t.rest.dur)*100):0)+'%';if(t.rest.run&&rest<=0){t.rest.run=false;toast('组间休息结束');notifyRestEnd();save()}}
function time(s){return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
function restTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function render(){renderPlan();renderAnalysis();renderArchive();renderTimer();save()}
function show(tab){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===tab));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='analysis')renderAnalysis();if(tab==='archive')renderArchive()}
function modal(msg){return new Promise(res=>{$('#modalMsg').textContent=msg;$('#modal').classList.add('show');window._modal=res})}
function events(){document.addEventListener('click',async e=>{const nav=e.target.closest('[data-tab]');if(nav)return show(nav.dataset.tab);const btn=e.target.closest('[data-action]');if(!btn)return;const a=btn.dataset.action;if(a==='toggle'){const row=btn.closest('.set-row'),s=checkin().c.exercises[+row.dataset.ex].sets[+row.dataset.set];s.done=!s.done;row.classList.toggle('done',s.done);btn.textContent=s.done?'✓':'';updateProgress()}if(a==='save'){const r=recordFromCheckin();if(!r.items.length)return toast('还没有勾选完成组');state.records=merge(state.records,[r]);delete state.checkins[state.active];render();toast('已保存，计划与分析已更新')}if(a==='reset'){if(await modal('确定清空今日打卡？')){delete state.checkins[state.active];renderPlan()}}if(a==='basketball'){const ctx=planContext();state.records=merge(state.records,[{date:ctx.date,items:[{name:'篮球',sets:[]}]}]);delete state.checkins[state.active];render();toast('已记录篮球/有氧')}if(a==='add'){const txt=$('#newLog').value.trim();if(txt){state.records=merge(state.records,parseRaw(txt));$('#newLog').value='';render();toast('已添加记录')}}if(a==='restore'){if(await modal('确定恢复默认完整档案？')){state=defaultState();render()}}if(a==='export'){const blob=new Blob([JSON.stringify(state.records,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),x=document.createElement('a');x.href=u;x.download='gym-vault-records.json';x.click();URL.revokeObjectURL(u)}if(a==='clearCache'){if('caches'in window)for(const k of await caches.keys())await caches.delete(k);if('serviceWorker'in navigator)for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();location.href=location.pathname+'?v=20&clean='+Date.now()}if(a==='work'){const w=state.timers.work;if(w.run){w.elapsed+=Date.now()-w.start;w.run=false}else{w.start=Date.now();w.run=true}renderTimer();save()}if(a==='workReset'){state.timers.work={run:false,start:0,elapsed:0};renderTimer();save()}if(a==='restSet'){state.timers.rest.dur=+btn.dataset.sec;state.timers.rest.run=false;renderTimer();save()}if(a==='rest'){const r=state.timers.rest;if(r.run){r.dur=Math.max(1,Math.ceil((r.end-Date.now())/1000));r.run=false}else{r.end=Date.now()+r.dur*1000;r.run=true}renderTimer();save()}if(a==='restAdd'){const r=state.timers.rest,sec=+btn.dataset.sec;if(r.run)r.end+=sec*1000;else r.dur=Math.max(10,r.dur+sec);renderTimer();save()}if(a==='restReset'){state.timers.rest.run=false;renderTimer();save()}if(a==='notify'){Notification?.requestPermission?.().then(async p=>{toast(p==='granted'?'提醒已开启':'未允许提醒');if(p==='granted'&&'serviceWorker' in navigator)await navigator.serviceWorker.ready})}if(a==='modalYes'||a==='modalNo'){$('#modal').classList.remove('show');window._modal?.(a==='modalYes')}});document.addEventListener('input',e=>{const inp=e.target.closest('.set-row input');if(!inp)return;const row=inp.closest('.set-row'),s=checkin().c.exercises[+row.dataset.ex].sets[+row.dataset.set];s[inp.dataset.field]=inp.value;save()})}
function waves(){const c=$('#waves'),ctx=c.getContext('2d');let run=true,t=0;function size(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);c._w=r.width;c._h=r.height}function draw(){if(!run)return;t+=.012;ctx.clearRect(0,0,c._w,c._h);ctx.lineWidth=1;for(let i=0;i<8;i++){ctx.beginPath();ctx.strokeStyle=`rgba(76,176,224,${.055+i*.007})`;for(let x=-20;x<c._w+20;x+=8){const y=80+i*74+Math.sin(x*.018+t+i)*12+Math.sin(x*.041-t*1.6)*4;x===-20?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke()}requestAnimationFrame(draw)}size();addEventListener('resize',size);document.addEventListener('visibilitychange',()=>{run=!document.hidden;if(run)draw()});draw()}
function boot(){try{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=20').catch(()=>{});events();render();setInterval(renderTimer,300);document.addEventListener('visibilitychange',()=>{renderTimer();save()});waves()}catch(err){console.error(err);$('#planTitle').textContent='脚本异常';$('#planDesc').textContent=err.message;toast('脚本异常：'+err.message)}}
boot();
})();